# Generated by Django 4.0.5 on 2022-06-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Souscripteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dateEffet', models.DateField()),
                ('dateEcheance', models.DateField()),
                ('assureur', models.CharField(max_length=100)),
                ('territorialite', models.CharField(max_length=100)),
                ('consultationGeneraliste', models.IntegerField()),
                ('consultationSpecialiste', models.IntegerField()),
                ('pharmacie', models.IntegerField()),
                ('vitamines', models.IntegerField()),
                ('vaccins', models.IntegerField()),
                ('hospitalisation', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
