# Generated by Django 4.0.5 on 2022-06-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souscripteurs', '0002_assureurs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assureurs',
            options={'ordering': ['-created']},
        ),
    ]
