# Generated by Django 4.0.5 on 2022-06-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('souscripteurs', '0003_alter_assureurs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscripteurs',
            name='assureur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscripteurs.assureurs'),
        ),
    ]
