# Generated by Django 4.0.5 on 2022-07-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souscripteurs', '0004_alter_souscripteurs_assureur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assureurs',
            new_name='Assureur',
        ),
        migrations.RenameModel(
            old_name='Souscripteurs',
            new_name='Souscripteur',
        ),
    ]
